# Generated by Django 5.2 on 2025-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('G', 'Gestor'), ('P', 'Professor')], default='', max_length=1),
        ),
    ]
