# Generated by Django 5.2 on 2025-05-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_hora',
            field=models.IntegerField(default=''),
        ),
    ]
